# Generated by Django 3.1 on 2021-02-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.EmailField(max_length=64),
        ),
    ]
