# Generated by Django 3.1 on 2021-02-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_auto_20210222_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
